# this needs improvements

set( CC65_MACHINE_TYPE "none" )
set( CC65_CPU "65c02" )
execute_process( COMMAND cl65 --print-target-path OUTPUT_VARIABLE CL65_TARGET_PATH OUTPUT_STRIP_TRAILING_WHITESPACE )
string( REGEX REPLACE "/target$" "" CC65_BASE "${CL65_TARGET_PATH}" )

message( "CC65_BASE = ${CC65_BASE}" )

set( CMAKE_C_COMPILER "cl65" )
set( CMAKE_C_FLAGS "--cpu ${CC65_CPU} -t ${CC65_MACHINE_TYPE}" )
set( CMAKE_C_LINK_EXECUTABLE "cl65 <FLAGS> <CMAKE_ASM_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> -Ln <TARGET_NAME>.labels <LINK_LIBRARIES>" )

set( CMAKE_ASM_COMPILER "cl65" )
set( CMAKE_ASM_FLAGS "--cpu ${CC65_CPU} -t ${CC65_MACHINE_TYPE}" )
set( CMAKE_ASM_LINK_EXECUTABLE "cl65 <FLAGS> <CMAKE_ASM_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> -Ln <TARGET_NAME>.labels <LINK_LIBRARIES>" )
set( CMAKE_ASM_SOURCE_FILE_EXTENSIONS s;S;asm )

set( CMAKE_EXECUTABLE_SUFFIX ".bin" )
