# this needs improvements

set( CMAKE_C_COMPILER "cl65" )
set( CMAKE_C_FLAGS "--cpu 65c02 -t none" )
set( CMAKE_C_LINK_EXECUTABLE "cl65 <FLAGS> <CMAKE_ASM_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> -Ln <TARGET_NAME>.labels <LINK_LIBRARIES>" )

set( CMAKE_ASM_COMPILER "cl65" )
set( CMAKE_ASM_FLAGS "--cpu 65c02 -t none" )
set( CMAKE_ASM_LINK_EXECUTABLE "cl65 <FLAGS> <CMAKE_ASM_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> -Ln <TARGET_NAME>.labels <LINK_LIBRARIES>" )
set( CMAKE_ASM_SOURCE_FILE_EXTENSIONS s;S;asm )

set( CMAKE_EXECUTABLE_SUFFIX ".bin" )
