
MAKEFILE_DIR   := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

LINK_CFG       ?= sorbus.cfg

CP             ?= cp
MKDIR          ?= mkdir -p
CC65_BASE_DIR  ?= $(dir $(shell cl65 --print-target-path))

AR65           ?= ar65
CA65           ?= ca65
CC65           ?= cc65
CL65           ?= cl65
LD65           ?= ld65

CC65_FLAGS     ?= -O
SYS_FLAGS      ?= --cpu 65sc02 -t none --cfg-path $(CFG_DIR) -C $(LINK_CFG)

EXPORT_DIR     ?= bin
CFG_DIR        ?= $(MAKEFILE_DIR)/cfg
SORBUS_LIB     ?= $(MAKEFILE_DIR)/lib/sorbus.lib
INCLUDE_DIR    ?= $(MAKEFILE_DIR)/include
