name: TestBuild

on: [push, pull_request]

permissions:
  contents: write

jobs:
  TestBuild:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v6

      - name: 'Install dependencies'
        run: |
          make setup-apt-build-only
          answer=yes src/tools/local-nstow.sh
          answer=yes src/tools/local-arm-none-eabi-toolchain.sh

      - name: 'Build'
        run: |
          make release

      - name: 'Release SorbusComputerCores.zip'
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: SorbusComputerCores.zip

